<?php

namespace App\Repositories;

use App\Models\Customer;
use App\Repositories\Contracts\CustomerRepositoryInterface;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Pagination\LengthAwarePaginator;

/**
 * CustomerRepository
 * 
 * Repository class for Customer model that implements CustomerRepositoryInterface.
 * This class provides data access layer methods for Customer operations
 * including CRUD operations, filtering, searching, and pagination.
 * 
 * @package App\Repositories
 * @author Generated by Laravel Custom Command
 */
class CustomerRepository implements CustomerRepositoryInterface
{
    /**
     * The Customer model instance.
     * 
     * @var Customer
     */
    protected Customer $model;

    /**
     * CustomerRepository constructor.
     * 
     * @param Customer $model The Customer model instance
     */
    public function __construct(Customer $model)
    {
        $this->model = $model;
    }

    /**
     * Get all Customers from the database.
     * 
     * This method retrieves all Customers records with optional eager loading
     * of related models to optimize database queries and prevent N+1 problems.
     * 
     * @param array $with Array of relationships to eager load (e.g., ['category', 'user'])
     * @return Collection Collection of Customer instances
     * 
     * @example
     * // Get all Customers without relationships
     * $customerRepository->getAll();
     * 
     * // Get all Customers with relationships
     * $customerRepository->getAll(['category', 'user']);
     */
    public function getAll(array $with = []): Collection
    {
        $query = $this->model->newQuery();

        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }

        return $query->get();
    }

    /**
     * Get paginated Customers with advanced filtering and relationship counting.
     * 
     * This method provides comprehensive pagination functionality with support for:
     * - Dynamic filtering based on provided criteria
     * - Eager loading of relationships to prevent N+1 queries
     * - Relationship counting for performance optimization
     * - Flexible sorting with security validation
     * 
     * @param array $filters Associative array of filter criteria:
     *                      - 'status': Filter by status field
     *                      - 'search': Search in name and description fields
     *                      - 'sort_by': Field to sort by (validated against allowed fields)
     *                      - 'sort_order': Sort direction ('asc' or 'desc')
     *                      - 'with_count': Array of relationships to count
     * @param array $with Array of relationships to eager load
     * @param int $perPage Number of records per page (default: 15)
     * @return LengthAwarePaginator Paginated collection of Customer instances
     * 
     * @example
     * // Basic pagination
     * $customerRepository->getPaginated();
     * 
     * // Pagination with filters and relationships
     * $customerRepository->getPaginated([
     *     'status' => 'active',
     *     'search' => 'keyword',
     *     'sort_by' => 'created_at',
     *     'sort_order' => 'desc',
     *     'with_count' => ['orders', 'reviews']
     * ], ['category', 'user'], 20);
     */
    public function getPaginated(array $filters = [], array $with = [], array $withCount = [], int $perPage = 15, string $sortBy = 'name', string $sortOrder = 'asc'): LengthAwarePaginator
    {
        $query = $this->model->newQuery();

        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }

        // Apply relationship counting for performance optimization
        if (!empty($withCount)) {
            $query->withCount($withCount);
        }

        // Apply dynamic filters
        $this->applyFilters($query, $filters);

        // Apply secure sorting with validation
        $allowedSortFields = ['id', 'name', 'phone', 'email', 'status', 'created_at', 'updated_at'];
        
        // Validate sort order
        $sortOrder = in_array(strtolower($sortOrder), ['asc', 'desc']) ? strtolower($sortOrder) : 'asc';

        // Apply sorting with field validation
        if (in_array($sortBy, $allowedSortFields)) {
            $query->orderBy($sortBy, $sortOrder);
        } else {
            // Default sorting if invalid field provided
            $query->orderBy('name', 'asc');
        }

        return $query->paginate($perPage);
    }

    /**
     * Find a specific Customer by its primary key (ID).
     * 
     * This method retrieves a single Customer record by its ID with optional
     * eager loading of related models. Returns null if no record is found.
     * 
     * @param int $id The primary key ID of the Customer to find
     * @param array $with Array of relationships to eager load
     * @return Customer|null The Customer instance or null if not found
     * 
     * @example
     * // Find Customer by ID without relationships
     * $customer = $customerRepository->findById(1);
     * 
     * // Find Customer by ID with relationships
     * $customer = $customerRepository->findById(1, ['category', 'user']);
     */
    public function findById(int $id, array $with = []): ?Customer
    {
        $query = $this->model->newQuery();

        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }

        return $query->find($id);
    }

    /**
     * Find a Customer by its name field.
     * 
     * This method performs an exact match search on the name field.
     * Use this when you need to find a Customer by its exact name.
     * 
     * @param string $name The exact name to search for
     * @param array $with Array of relationships to eager load
     * @return Customer|null The Customer instance or null if not found
     * 
     * @example
     * // Find Customer by exact name
     * $customer = $customerRepository->findByName('Product Name');
     * 
     * // Find Customer by name with relationships
     * $customer = $customerRepository->findByName('Product Name', ['category']);
     */
    public function findByName(string $name, array $with = []): ?Customer
    {
        $query = $this->model->newQuery();

        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }

        return $query->where('name', $name)->first();
    }

    /**
     * Create a new Customer record in the database.
     * 
     * This method creates a new Customer instance with the provided data.
     * The data array should contain all required fields for the Customer.
     * 
     * @param array $data Associative array of Customer attributes
     * @return Customer The newly created Customer instance
     * 
     * @throws \Illuminate\Database\QueryException If database constraints are violated
     * 
     * @example
     * // Create a new Customer
     * $customer = $customerRepository->create([
     *     'name' => 'New Customer',
     *     'status' => 'active',
     *     'description' => 'Description here'
     * ]);
     */
    public function create(array $data): Customer
    {
        return $this->model->create($data);
    }

    /**
     * Update an existing Customer record.
     * 
     * This method updates the specified Customer instance with new data
     * and returns the refreshed model instance from the database.
     * 
     * @param Customer $customer The Customer instance to update
     * @param array $data Associative array of attributes to update
     * @return Customer The updated Customer instance with fresh data from database
     * 
     * @throws \Illuminate\Database\QueryException If database constraints are violated
     * 
     * @example
     * // Update a Customer
     * $updatedCustomer = $customerRepository->update($customer, [
     *     'name' => 'Updated Name',
     *     'status' => 'inactive'
     * ]);
     */
    public function update(Customer $customer, array $data): Customer
    {
        $customer->update($data);
        return $customer->fresh();
    }

    /**
     * Delete a Customer record from the database.
     * 
     * This method performs a soft delete if the model uses SoftDeletes trait,
     * otherwise it permanently removes the record from the database.
     * 
     * @param Customer $customer The Customer instance to delete
     * @return bool True if deletion was successful, false otherwise
     * 
     * @throws \Exception If the model cannot be deleted due to constraints
     * 
     * @example
     * // Delete a Customer
     * $success = $customerRepository->delete($customer);
     * if ($success) {
     *     // Handle successful deletion
     * }
     */
    public function delete(Customer $customer): bool
    {
        return $customer->delete();
    }

    /**
     * Get all Customers filtered by status.
     * 
     * This method retrieves all Customers that match the specified status.
     * Commonly used statuses include 'active', 'inactive', 'pending', etc.
     * 
     * @param string $status The status value to filter by
     * @param array $with Array of relationships to eager load
     * @return Collection Collection of Customer instances with the specified status
     * 
     * @example
     * // Get all active Customers
     * $activeCustomers = $customerRepository->getByStatus('active');
     * 
     * // Get inactive Customers with relationships
     * $inactiveCustomers = $customerRepository->getByStatus('inactive', ['category']);
     */
    public function getByStatus(string $status, array $with = []): Collection
    {
        $query = $this->model->newQuery();

        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }

        return $query->where('status', $status)->get();
    }

    /**
     * Get active Customers.
     */
    public function getActiveCustomers(array $with = []): Collection
    {
        return $this->getByStatus('active', $with);
    }

    /**
     * Search Customers.
     */
    public function search(string $query, array $with = [], int $perPage = 15): LengthAwarePaginator
    {
        $queryBuilder = $this->model->newQuery();

        if (!empty($with)) {
            $queryBuilder->with($with);
        }

        $queryBuilder->where(function ($q) use ($query) {
            $q->where('name', 'LIKE', "%{$query}%")
              ->orWhere('phone', 'LIKE', "%{$query}%")
              ->orWhere('email', 'LIKE', "%{$query}%")
              ->orWhere('address', 'LIKE', "%{$query}%");
        });

        return $queryBuilder->paginate($perPage);
    }

    /**
     * Check if Customer name exists.
     */
    public function nameExists(string $name, ?int $excludeId = null): bool
    {
        $query = $this->model->where('name', $name);

        if ($excludeId) {
            $query->where('id', '!=', $excludeId);
        }

        return $query->exists();
    }

    /**
     * Get Customer statistics.
     */
    public function getStatistics(): array
    {
        $totalCustomers = $this->model->count();
        $activeCustomers = $this->model->where('status', 'active')->count();
        $inactiveCustomers = $this->model->where('status', 'inactive')->count();
        
        return [
            'total_customers' => $totalCustomers,
            'active_customers' => $activeCustomers,
            'inactive_customers' => $inactiveCustomers,
        ];
    }

    /**
     * Check if Customer has related records.
     */
    public function hasRelatedRecords(int $customerId): bool
    {
        // Implement your business logic to check related records
        // Example: return $this->model->find($customerId)?->relatedModel()->exists() ?? false;
        return false;
    }

    /**
     * Apply dynamic filters to the query builder.
     * 
     * This protected method applies various filters to the query based on the
     * provided filters array. It supports status filtering, text search,
     * and can be extended with additional filter types.
     * 
     * @param \Illuminate\Database\Eloquent\Builder $query The query builder instance
     * @param array $filters Associative array of filter criteria
     * @return void
     * 
     * @example
     * // This method is called internally by other repository methods
     * // Supported filters:
     * // - 'status': Filter by exact status match
     * // - 'search': Search in name and description fields (case-insensitive)
     * // - Add custom filters as needed in your implementation
     */
    protected function applyFilters($query, array $filters): void
    {
        // Filter by status if provided
        if (isset($filters['status'])) {
            $query->where('status', $filters['status']);
        }

        // Apply text search across multiple fields
        if (isset($filters['search'])) {
            $search = $filters['search'];
            $query->where(function ($q) use ($search) {
                $q->where('name', 'LIKE', "%{$search}%")
                  ->orWhere('description', 'LIKE', "%{$search}%");
                // Add more searchable fields as needed for your specific model
            });
        }

        // Add more custom filters as needed for your specific use case
        // Example: Category filter
        // if (isset($filters['category_id'])) {
        //     $query->where('category_id', $filters['category_id']);
        // }
        
        // Example: Date range filter
        // if (isset($filters['date_from'])) {
        //     $query->where('created_at', '>=', $filters['date_from']);
        // }
        // if (isset($filters['date_to'])) {
        //     $query->where('created_at', '<=', $filters['date_to']);
        // }
    }
}