<?php

namespace App\Repositories;

use App\Models\Payment;
use App\Repositories\Contracts\PaymentRepositoryInterface;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Pagination\LengthAwarePaginator;

/**
 * PaymentRepository
 * 
 * Repository class for Payment model that implements PaymentRepositoryInterface.
 * This class provides data access layer methods for Payment operations
 * including CRUD operations, filtering, searching, and pagination.
 * 
 * @package App\Repositories
 * @author Generated by Laravel Custom Command
 */
class PaymentRepository implements PaymentRepositoryInterface
{
    /**
     * The Payment model instance.
     * 
     * @var Payment
     */
    protected Payment $model;

    /**
     * PaymentRepository constructor.
     * 
     * @param Payment $model The Payment model instance
     */
    public function __construct(Payment $model)
    {
        $this->model = $model;
    }

    /**
     * Get all Payments from the database.
     * 
     * This method retrieves all Payments records with optional eager loading
     * of related models to optimize database queries and prevent N+1 problems.
     * 
     * @param array $with Array of relationships to eager load (e.g., ['category', 'user'])
     * @return Collection Collection of Payment instances
     * 
     * @example
     * // Get all Payments without relationships
     * $paymentRepository->getAll();
     * 
     * // Get all Payments with relationships
     * $paymentRepository->getAll(['category', 'user']);
     */
    public function getAll(array $with = []): Collection
    {
        $query = $this->model->newQuery();

        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }

        return $query->get();
    }

    /**
     * Get paginated Payments with advanced filtering and relationship counting.
     * 
     * This method provides comprehensive pagination functionality with support for:
     * - Dynamic filtering based on provided criteria
     * - Eager loading of relationships to prevent N+1 queries
     * - Relationship counting for performance optimization
     * - Flexible sorting with security validation
     * 
     * @param array $filters Associative array of filter criteria:
     *                      - 'status': Filter by status field
     *                      - 'search': Search in name and description fields
     *                      - 'sort_by': Field to sort by (validated against allowed fields)
     *                      - 'sort_order': Sort direction ('asc' or 'desc')
     *                      - 'with_count': Array of relationships to count
     * @param array $with Array of relationships to eager load
     * @param int $perPage Number of records per page (default: 15)
     * @return LengthAwarePaginator Paginated collection of Payment instances
     * 
     * @example
     * // Basic pagination
     * $paymentRepository->getPaginated();
     * 
     * // Pagination with filters and relationships
     * $paymentRepository->getPaginated([
     *     'status' => 'active',
     *     'search' => 'keyword',
     *     'sort_by' => 'created_at',
     *     'sort_order' => 'desc',
     *     'with_count' => ['orders', 'reviews']
     * ], ['category', 'user'], 20);
     */
    public function getPaginated(array $filters = [], array $with = [], int $perPage = 15): LengthAwarePaginator
    {
        $query = $this->model->newQuery();

        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }

        // Apply relationship counting for performance optimization
        if (isset($filters['with_count']) && !empty($filters['with_count'])) {
            $query->withCount($filters['with_count']);
        }

        // Apply dynamic filters
        $this->applyFilters($query, $filters);

        // Apply secure sorting with validation
        $allowedSortFields = ['id', 'name', 'status', 'created_at', 'updated_at'];
        $sortBy = $filters['sort_by'] ?? 'name';
        $sortOrder = strtolower($filters['sort_order'] ?? 'asc');
        
        // Validate sort order
        $sortOrder = in_array($sortOrder, ['asc', 'desc']) ? $sortOrder : 'asc';

        // Apply sorting with field validation
        if (in_array($sortBy, $allowedSortFields)) {
            $query->orderBy($sortBy, $sortOrder);
        } else {
            // Default sorting if invalid field provided
            $query->orderBy('name', 'asc');
        }

        return $query->paginate($perPage);
    }

    /**
     * Find a specific Payment by its primary key (ID).
     * 
     * This method retrieves a single Payment record by its ID with optional
     * eager loading of related models. Returns null if no record is found.
     * 
     * @param int $id The primary key ID of the Payment to find
     * @param array $with Array of relationships to eager load
     * @return Payment|null The Payment instance or null if not found
     * 
     * @example
     * // Find Payment by ID without relationships
     * $payment = $paymentRepository->findById(1);
     * 
     * // Find Payment by ID with relationships
     * $payment = $paymentRepository->findById(1, ['category', 'user']);
     */
    public function findById(int $id, array $with = []): ?Payment
    {
        $query = $this->model->newQuery();

        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }

        return $query->find($id);
    }

    /**
     * Find a Payment by its name field.
     * 
     * This method performs an exact match search on the name field.
     * Use this when you need to find a Payment by its exact name.
     * 
     * @param string $name The exact name to search for
     * @param array $with Array of relationships to eager load
     * @return Payment|null The Payment instance or null if not found
     * 
     * @example
     * // Find Payment by exact name
     * $payment = $paymentRepository->findByName('Product Name');
     * 
     * // Find Payment by name with relationships
     * $payment = $paymentRepository->findByName('Product Name', ['category']);
     */
    public function findByName(string $name, array $with = []): ?Payment
    {
        $query = $this->model->newQuery();

        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }

        return $query->where('name', $name)->first();
    }

    /**
     * Create a new Payment record in the database.
     * 
     * This method creates a new Payment instance with the provided data.
     * The data array should contain all required fields for the Payment.
     * 
     * @param array $data Associative array of Payment attributes
     * @return Payment The newly created Payment instance
     * 
     * @throws \Illuminate\Database\QueryException If database constraints are violated
     * 
     * @example
     * // Create a new Payment
     * $payment = $paymentRepository->create([
     *     'name' => 'New Payment',
     *     'status' => 'active',
     *     'description' => 'Description here'
     * ]);
     */
    public function create(array $data): Payment
    {
        return $this->model->create($data);
    }

    /**
     * Update an existing Payment record.
     * 
     * This method updates the specified Payment instance with new data
     * and returns the refreshed model instance from the database.
     * 
     * @param Payment $payment The Payment instance to update
     * @param array $data Associative array of attributes to update
     * @return Payment The updated Payment instance with fresh data from database
     * 
     * @throws \Illuminate\Database\QueryException If database constraints are violated
     * 
     * @example
     * // Update a Payment
     * $updatedPayment = $paymentRepository->update($payment, [
     *     'name' => 'Updated Name',
     *     'status' => 'inactive'
     * ]);
     */
    public function update(Payment $payment, array $data): Payment
    {
        $payment->update($data);
        return $payment->fresh();
    }

    /**
     * Delete a Payment record from the database.
     * 
     * This method performs a soft delete if the model uses SoftDeletes trait,
     * otherwise it permanently removes the record from the database.
     * 
     * @param Payment $payment The Payment instance to delete
     * @return bool True if deletion was successful, false otherwise
     * 
     * @throws \Exception If the model cannot be deleted due to constraints
     * 
     * @example
     * // Delete a Payment
     * $success = $paymentRepository->delete($payment);
     * if ($success) {
     *     // Handle successful deletion
     * }
     */
    public function delete(Payment $payment): bool
    {
        return $payment->delete();
    }

    /**
     * Get all Payments filtered by status.
     * 
     * This method retrieves all Payments that match the specified status.
     * Commonly used statuses include 'active', 'inactive', 'pending', etc.
     * 
     * @param string $status The status value to filter by
     * @param array $with Array of relationships to eager load
     * @return Collection Collection of Payment instances with the specified status
     * 
     * @example
     * // Get all active Payments
     * $activePayments = $paymentRepository->getByStatus('active');
     * 
     * // Get inactive Payments with relationships
     * $inactivePayments = $paymentRepository->getByStatus('inactive', ['category']);
     */
    public function getByStatus(string $status, array $with = []): Collection
    {
        $query = $this->model->newQuery();

        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }

        return $query->where('status', $status)->get();
    }

    /**
     * Get active Payments.
     */
    public function getActivePayments(array $with = []): Collection
    {
        return $this->getByStatus('active', $with);
    }

    /**
     * Search Payments.
     */
    public function search(string $query, array $with = [], int $perPage = 15): LengthAwarePaginator
    {
        $queryBuilder = $this->model->newQuery();

        if (!empty($with)) {
            $queryBuilder->with($with);
        }

        $queryBuilder->where(function ($q) use ($query) {
            $q->where('name', 'LIKE', "%{$query}%")
              ->orWhere('description', 'LIKE', "%{$query}%");
            // Add more searchable fields as needed
        });

        return $queryBuilder->paginate($perPage);
    }

    /**
     * Check if Payment name exists.
     */
    public function nameExists(string $name, ?int $excludeId = null): bool
    {
        $query = $this->model->where('name', $name);

        if ($excludeId) {
            $query->where('id', '!=', $excludeId);
        }

        return $query->exists();
    }

    /**
     * Get Payment statistics.
     */
    public function getStatistics(): array
    {
        $totalPayments = $this->model->count();
        $activePayments = $this->model->where('status', 'active')->count();
        $inactivePayments = $this->model->where('status', 'inactive')->count();
        
        return [
            'total_payments' => $totalPayments,
            'active_payments' => $activePayments,
            'inactive_payments' => $inactivePayments,
        ];
    }

    /**
     * Check if Payment has related records.
     */
    public function hasRelatedRecords(int $paymentId): bool
    {
        // Implement your business logic to check related records
        // Example: return $this->model->find($paymentId)?->relatedModel()->exists() ?? false;
        return false;
    }

    /**
     * Apply dynamic filters to the query builder.
     * 
     * This protected method applies various filters to the query based on the
     * provided filters array. It supports status filtering, text search,
     * and can be extended with additional filter types.
     * 
     * @param \Illuminate\Database\Eloquent\Builder $query The query builder instance
     * @param array $filters Associative array of filter criteria
     * @return void
     * 
     * @example
     * // This method is called internally by other repository methods
     * // Supported filters:
     * // - 'status': Filter by exact status match
     * // - 'search': Search in name and description fields (case-insensitive)
     * // - Add custom filters as needed in your implementation
     */
    protected function applyFilters($query, array $filters): void
    {
        // Filter by status if provided
        if (isset($filters['status'])) {
            $query->where('status', $filters['status']);
        }

        // Apply text search across multiple fields
        if (isset($filters['search'])) {
            $search = $filters['search'];
            $query->where(function ($q) use ($search) {
                $q->where('name', 'LIKE', "%{$search}%")
                  ->orWhere('description', 'LIKE', "%{$search}%");
                // Add more searchable fields as needed for your specific model
            });
        }

        // Add more custom filters as needed for your specific use case
        // Example: Category filter
        // if (isset($filters['category_id'])) {
        //     $query->where('category_id', $filters['category_id']);
        // }
        
        // Example: Date range filter
        // if (isset($filters['date_from'])) {
        //     $query->where('created_at', '>=', $filters['date_from']);
        // }
        // if (isset($filters['date_to'])) {
        //     $query->where('created_at', '<=', $filters['date_to']);
        // }
    }
}