<?php

namespace App\Repositories;

use App\Models\SalesTransaction;
use App\Repositories\Contracts\SalesTransactionRepositoryInterface;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Pagination\LengthAwarePaginator;

/**
 * SalesTransactionRepository
 * 
 * Repository class for SalesTransaction model that implements SalesTransactionRepositoryInterface.
 * This class provides data access layer methods for SalesTransaction operations
 * including CRUD operations, filtering, searching, and pagination.
 * 
 * @package App\Repositories
 * @author Generated by Laravel Custom Command
 */
class SalesTransactionRepository implements SalesTransactionRepositoryInterface
{
    /**
     * The SalesTransaction model instance.
     * 
     * @var SalesTransaction
     */
    protected SalesTransaction $model;

    /**
     * SalesTransactionRepository constructor.
     * 
     * @param SalesTransaction $model The SalesTransaction model instance
     */
    public function __construct(SalesTransaction $model)
    {
        $this->model = $model;
    }

    /**
     * Get all SalesTransactions from the database.
     * 
     * This method retrieves all SalesTransactions records with optional eager loading
     * of related models to optimize database queries and prevent N+1 problems.
     * 
     * @param array $with Array of relationships to eager load (e.g., ['category', 'user'])
     * @return Collection Collection of SalesTransaction instances
     * 
     * @example
     * // Get all SalesTransactions without relationships
     * $salesTransactionRepository->getAll();
     * 
     * // Get all SalesTransactions with relationships
     * $salesTransactionRepository->getAll(['category', 'user']);
     */
    public function getAll(array $with = []): Collection
    {
        $query = $this->model->newQuery();

        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }

        return $query->get();
    }

    /**
     * Get paginated SalesTransactions with advanced filtering and relationship counting.
     * 
     * This method provides comprehensive pagination functionality with support for:
     * - Dynamic filtering based on provided criteria
     * - Eager loading of relationships to prevent N+1 queries
     * - Relationship counting for performance optimization
     * - Flexible sorting with security validation
     * 
     * @param array $filters Associative array of filter criteria:
     *                      - 'status': Filter by status field
     *                      - 'search': Search in name and description fields
     *                      - 'sort_by': Field to sort by (validated against allowed fields)
     *                      - 'sort_order': Sort direction ('asc' or 'desc')
     *                      - 'with_count': Array of relationships to count
     * @param array $with Array of relationships to eager load
     * @param int $perPage Number of records per page (default: 15)
     * @return LengthAwarePaginator Paginated collection of SalesTransaction instances
     * 
     * @example
     * // Basic pagination
     * $salesTransactionRepository->getPaginated();
     * 
     * // Pagination with filters and relationships
     * $salesTransactionRepository->getPaginated([
     *     'status' => 'active',
     *     'search' => 'keyword',
     *     'sort_by' => 'created_at',
     *     'sort_order' => 'desc',
     *     'with_count' => ['orders', 'reviews']
     * ], ['category', 'user'], 20);
     */
    public function getPaginated(array $filters = [], array $with = [], int $perPage = 15): LengthAwarePaginator
    {
        $query = $this->model->newQuery();

        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }

        // Apply relationship counting for performance optimization
        if (isset($filters['with_count']) && !empty($filters['with_count'])) {
            $query->withCount($filters['with_count']);
        }

        // Apply dynamic filters
        $this->applyFilters($query, $filters);

        // Apply secure sorting with validation
        $allowedSortFields = ['id', 'name', 'status', 'created_at', 'updated_at'];
        $sortBy = $filters['sort_by'] ?? 'name';
        $sortOrder = strtolower($filters['sort_order'] ?? 'asc');
        
        // Validate sort order
        $sortOrder = in_array($sortOrder, ['asc', 'desc']) ? $sortOrder : 'asc';

        // Apply sorting with field validation
        if (in_array($sortBy, $allowedSortFields)) {
            $query->orderBy($sortBy, $sortOrder);
        } else {
            // Default sorting if invalid field provided
            $query->orderBy('name', 'asc');
        }

        return $query->paginate($perPage);
    }

    /**
     * Find a specific SalesTransaction by its primary key (ID).
     * 
     * This method retrieves a single SalesTransaction record by its ID with optional
     * eager loading of related models. Returns null if no record is found.
     * 
     * @param int $id The primary key ID of the SalesTransaction to find
     * @param array $with Array of relationships to eager load
     * @return SalesTransaction|null The SalesTransaction instance or null if not found
     * 
     * @example
     * // Find SalesTransaction by ID without relationships
     * $salesTransaction = $salesTransactionRepository->findById(1);
     * 
     * // Find SalesTransaction by ID with relationships
     * $salesTransaction = $salesTransactionRepository->findById(1, ['category', 'user']);
     */
    public function findById(int $id, array $with = []): ?SalesTransaction
    {
        $query = $this->model->newQuery();

        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }

        return $query->find($id);
    }

    /**
     * Find a SalesTransaction by its name field.
     * 
     * This method performs an exact match search on the name field.
     * Use this when you need to find a SalesTransaction by its exact name.
     * 
     * @param string $name The exact name to search for
     * @param array $with Array of relationships to eager load
     * @return SalesTransaction|null The SalesTransaction instance or null if not found
     * 
     * @example
     * // Find SalesTransaction by exact name
     * $salesTransaction = $salesTransactionRepository->findByName('Product Name');
     * 
     * // Find SalesTransaction by name with relationships
     * $salesTransaction = $salesTransactionRepository->findByName('Product Name', ['category']);
     */
    public function findByName(string $name, array $with = []): ?SalesTransaction
    {
        $query = $this->model->newQuery();

        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }

        return $query->where('name', $name)->first();
    }

    /**
     * Create a new SalesTransaction record in the database.
     * 
     * This method creates a new SalesTransaction instance with the provided data.
     * The data array should contain all required fields for the SalesTransaction.
     * 
     * @param array $data Associative array of SalesTransaction attributes
     * @return SalesTransaction The newly created SalesTransaction instance
     * 
     * @throws \Illuminate\Database\QueryException If database constraints are violated
     * 
     * @example
     * // Create a new SalesTransaction
     * $salesTransaction = $salesTransactionRepository->create([
     *     'name' => 'New SalesTransaction',
     *     'status' => 'active',
     *     'description' => 'Description here'
     * ]);
     */
    public function create(array $data): SalesTransaction
    {
        return $this->model->create($data);
    }

    /**
     * Update an existing SalesTransaction record.
     * 
     * This method updates the specified SalesTransaction instance with new data
     * and returns the refreshed model instance from the database.
     * 
     * @param SalesTransaction $salesTransaction The SalesTransaction instance to update
     * @param array $data Associative array of attributes to update
     * @return SalesTransaction The updated SalesTransaction instance with fresh data from database
     * 
     * @throws \Illuminate\Database\QueryException If database constraints are violated
     * 
     * @example
     * // Update a SalesTransaction
     * $updatedSalesTransaction = $salesTransactionRepository->update($salesTransaction, [
     *     'name' => 'Updated Name',
     *     'status' => 'inactive'
     * ]);
     */
    public function update(SalesTransaction $salesTransaction, array $data): SalesTransaction
    {
        $salesTransaction->update($data);
        return $salesTransaction->fresh();
    }

    /**
     * Delete a SalesTransaction record from the database.
     * 
     * This method performs a soft delete if the model uses SoftDeletes trait,
     * otherwise it permanently removes the record from the database.
     * 
     * @param SalesTransaction $salesTransaction The SalesTransaction instance to delete
     * @return bool True if deletion was successful, false otherwise
     * 
     * @throws \Exception If the model cannot be deleted due to constraints
     * 
     * @example
     * // Delete a SalesTransaction
     * $success = $salesTransactionRepository->delete($salesTransaction);
     * if ($success) {
     *     // Handle successful deletion
     * }
     */
    public function delete(SalesTransaction $salesTransaction): bool
    {
        return $salesTransaction->delete();
    }

    /**
     * Get all SalesTransactions filtered by status.
     * 
     * This method retrieves all SalesTransactions that match the specified status.
     * Commonly used statuses include 'active', 'inactive', 'pending', etc.
     * 
     * @param string $status The status value to filter by
     * @param array $with Array of relationships to eager load
     * @return Collection Collection of SalesTransaction instances with the specified status
     * 
     * @example
     * // Get all active SalesTransactions
     * $activeSalesTransactions = $salesTransactionRepository->getByStatus('active');
     * 
     * // Get inactive SalesTransactions with relationships
     * $inactiveSalesTransactions = $salesTransactionRepository->getByStatus('inactive', ['category']);
     */
    public function getByStatus(string $status, array $with = []): Collection
    {
        $query = $this->model->newQuery();

        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }

        return $query->where('status', $status)->get();
    }

    /**
     * Get active SalesTransactions.
     */
    public function getActiveSalesTransactions(array $with = []): Collection
    {
        return $this->getByStatus('active', $with);
    }

    /**
     * Search SalesTransactions.
     */
    public function search(string $query, array $with = [], int $perPage = 15): LengthAwarePaginator
    {
        $queryBuilder = $this->model->newQuery();

        if (!empty($with)) {
            $queryBuilder->with($with);
        }

        $queryBuilder->where(function ($q) use ($query) {
            $q->where('name', 'LIKE', "%{$query}%")
              ->orWhere('description', 'LIKE', "%{$query}%");
            // Add more searchable fields as needed
        });

        return $queryBuilder->paginate($perPage);
    }

    /**
     * Check if SalesTransaction name exists.
     */
    public function nameExists(string $name, ?int $excludeId = null): bool
    {
        $query = $this->model->where('name', $name);

        if ($excludeId) {
            $query->where('id', '!=', $excludeId);
        }

        return $query->exists();
    }

    /**
     * Get SalesTransaction statistics.
     */
    public function getStatistics(): array
    {
        $totalSalesTransactions = $this->model->count();
        $activeSalesTransactions = $this->model->where('status', 'active')->count();
        $inactiveSalesTransactions = $this->model->where('status', 'inactive')->count();
        
        return [
            'total_sales_transactions' => $totalSalesTransactions,
            'active_sales_transactions' => $activeSalesTransactions,
            'inactive_sales_transactions' => $inactiveSalesTransactions,
        ];
    }

    /**
     * Check if SalesTransaction has related records.
     */
    public function hasRelatedRecords(int $salesTransactionId): bool
    {
        // Implement your business logic to check related records
        // Example: return $this->model->find($salesTransactionId)?->relatedModel()->exists() ?? false;
        return false;
    }

    /**
     * Apply dynamic filters to the query builder.
     * 
     * This protected method applies various filters to the query based on the
     * provided filters array. It supports status filtering, text search,
     * and can be extended with additional filter types.
     * 
     * @param \Illuminate\Database\Eloquent\Builder $query The query builder instance
     * @param array $filters Associative array of filter criteria
     * @return void
     * 
     * @example
     * // This method is called internally by other repository methods
     * // Supported filters:
     * // - 'status': Filter by exact status match
     * // - 'search': Search in name and description fields (case-insensitive)
     * // - Add custom filters as needed in your implementation
     */
    protected function applyFilters($query, array $filters): void
    {
        // Filter by status if provided
        if (isset($filters['status'])) {
            $query->where('status', $filters['status']);
        }

        // Apply text search across multiple fields
        if (isset($filters['search'])) {
            $search = $filters['search'];
            $query->where(function ($q) use ($search) {
                $q->where('name', 'LIKE', "%{$search}%")
                  ->orWhere('description', 'LIKE', "%{$search}%");
                // Add more searchable fields as needed for your specific model
            });
        }

        // Add more custom filters as needed for your specific use case
        // Example: Category filter
        // if (isset($filters['category_id'])) {
        //     $query->where('category_id', $filters['category_id']);
        // }
        
        // Example: Date range filter
        // if (isset($filters['date_from'])) {
        //     $query->where('created_at', '>=', $filters['date_from']);
        // }
        // if (isset($filters['date_to'])) {
        //     $query->where('created_at', '<=', $filters['date_to']);
        // }
    }
}