<?php

namespace App\Repositories;

use App\Models\Supplier;
use App\Repositories\Contracts\SupplierRepositoryInterface;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Pagination\LengthAwarePaginator;

/**
 * SupplierRepository
 * 
 * Repository class for Supplier model that implements SupplierRepositoryInterface.
 * This class provides data access layer methods for Supplier operations
 * including CRUD operations, filtering, searching, and pagination.
 * 
 * @package App\Repositories
 * @author Generated by Laravel Custom Command
 */
class SupplierRepository implements SupplierRepositoryInterface
{
    /**
     * The Supplier model instance.
     * 
     * @var Supplier
     */
    protected Supplier $model;

    /**
     * SupplierRepository constructor.
     * 
     * @param Supplier $model The Supplier model instance
     */
    public function __construct(Supplier $model)
    {
        $this->model = $model;
    }

    /**
     * Get all Suppliers from the database.
     * 
     * This method retrieves all Suppliers records with optional eager loading
     * of related models to optimize database queries and prevent N+1 problems.
     * 
     * @param array $with Array of relationships to eager load (e.g., ['purchaseOrders'])
     * @return Collection Collection of Supplier instances
     * 
     * @example
     * // Get all Suppliers without relationships
     * $supplierRepository->getAll();
     * 
     * // Get all Suppliers with purchase orders
     * $supplierRepository->getAll(['purchaseOrders']);
     */
    public function getAll(array $with = []): Collection
    {
        $query = $this->model->newQuery();
        
        if (!empty($with)) {
            $query->with($with);
        }
        
        return $query->get();
    }

    /**
     * Get paginated Suppliers with optional filters and relationships.
     * 
     * This method provides paginated results with filtering capabilities
     * for efficient data retrieval and display in user interfaces.
     * 
     * @param array $filters Associative array of filters to apply
     * @param array $with Array of relationships to eager load
     * @param int $perPage Number of items per page (default: 15)
     * @return LengthAwarePaginator Paginated collection of Supplier instances
     * 
     * @example
     * // Get paginated suppliers with filters
     * $filters = ['status' => 'active', 'search' => 'supplier name'];
     * $supplierRepository->getPaginated($filters, ['purchaseOrders'], 10);
     */
    public function getPaginated(array $filters = [], array $with = [], array $withCount = [], int $perPage = 15, string $sortBy = 'name', string $sortOrder = 'asc'): LengthAwarePaginator
    {
        $query = $this->model->newQuery();
        
        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }
        
        // Apply relationship counting for performance optimization
        if (!empty($withCount)) {
            $query->withCount($withCount);
        }
        
        // Apply dynamic filters
        $this->applyFilters($query, $filters);
        
        // Apply secure sorting with validation
        $allowedSortFields = ['id', 'name', 'phone', 'email', 'status', 'created_at', 'updated_at'];
        
        // Validate sort order
        $sortOrder = in_array(strtolower($sortOrder), ['asc', 'desc']) ? strtolower($sortOrder) : 'asc';

        // Apply sorting with field validation
        if (in_array($sortBy, $allowedSortFields)) {
            $query->orderBy($sortBy, $sortOrder);
        } else {
            // Default sorting if invalid field provided
            $query->orderBy('name', 'asc');
        }
        
        return $query->paginate($perPage);
    }

    /**
     * Find a Supplier by its ID.
     * 
     * @param int $id The Supplier ID to search for
     * @param array $with Array of relationships to eager load
     * @return Supplier|null The found Supplier instance or null if not found
     * 
     * @example
     * // Find supplier by ID with purchase orders
     * $supplier = $supplierRepository->findById(1, ['purchaseOrders']);
     */
    public function findById(int $id, array $with = []): ?Supplier
    {
        $query = $this->model->newQuery();
        
        if (!empty($with)) {
            $query->with($with);
        }
        
        return $query->find($id);
    }

    /**
     * Find a Supplier by its name.
     * 
     * @param string $name The Supplier name to search for
     * @param array $with Array of relationships to eager load
     * @return Supplier|null The found Supplier instance or null if not found
     */
    public function findByName(string $name, array $with = []): ?Supplier
    {
        $query = $this->model->newQuery();
        
        if (!empty($with)) {
            $query->with($with);
        }
        
        return $query->where('name', $name)->first();
    }

    /**
     * Create a new Supplier record.
     * 
     * @param array $data The data to create the Supplier with
     * @return Supplier The newly created Supplier instance
     * 
     * @example
     * $data = [
     *     'name' => 'ABC Supplier',
     *     'contact_person' => 'John Doe',
     *     'phone' => '123456789',
     *     'email' => 'john@abc.com',
     *     'address' => '123 Main St',
     *     'status' => 'active'
     * ];
     * $supplier = $supplierRepository->create($data);
     */
    public function create(array $data): Supplier
    {
        return $this->model->create($data);
    }

    /**
     * Update an existing Supplier record.
     * 
     * @param Supplier $supplier The Supplier instance to update
     * @param array $data The data to update the Supplier with
     * @return Supplier The updated Supplier instance
     */
    public function update(Supplier $supplier, array $data): Supplier
    {
        $supplier->update($data);
        return $supplier->fresh();
    }

    /**
     * Delete a Supplier record.
     * 
     * @param Supplier $supplier The Supplier instance to delete
     * @return bool True if deletion was successful, false otherwise
     */
    public function delete(Supplier $supplier): bool
    {
        return $supplier->delete();
    }

    /**
     * Get Suppliers by status.
     * 
     * @param string $status The status to filter by ('active' or 'inactive')
     * @param array $with Array of relationships to eager load
     * @return Collection Collection of Supplier instances
     */
    public function getByStatus(string $status, array $with = []): Collection
    {
        $query = $this->model->newQuery();
        
        if (!empty($with)) {
            $query->with($with);
        }
        
        return $query->where('status', $status)->get();
    }

    /**
     * Get active Suppliers.
     * 
     * @param array $with Array of relationships to eager load
     * @return Collection Collection of active Supplier instances
     */
    public function getActiveSuppliers(array $with = []): Collection
    {
        return $this->getByStatus('active', $with);
    }

    /**
     * Search Suppliers by name, contact person, phone, or email.
     * 
     * @param string $query The search query
     * @param array $with Array of relationships to eager load
     * @param int $perPage Number of items per page
     * @return LengthAwarePaginator Paginated search results
     */
    public function search(string $query, array $with = [], int $perPage = 15): LengthAwarePaginator
    {
        $queryBuilder = $this->model->newQuery();
        
        if (!empty($with)) {
            $queryBuilder->with($with);
        }
        
        $queryBuilder->where(function ($q) use ($query) {
            $q->where('name', 'LIKE', "%{$query}%")
              ->orWhere('contact_person', 'LIKE', "%{$query}%")
              ->orWhere('phone', 'LIKE', "%{$query}%")
              ->orWhere('email', 'LIKE', "%{$query}%");
        });
        
        return $queryBuilder->paginate($perPage);
    }

    /**
     * Check if a Supplier name already exists.
     * 
     * @param string $name The name to check
     * @param int|null $excludeId ID to exclude from the check (for updates)
     * @return bool True if name exists, false otherwise
     */
    public function nameExists(string $name, ?int $excludeId = null): bool
    {
        $query = $this->model->where('name', $name);
        
        if ($excludeId) {
            $query->where('id', '!=', $excludeId);
        }
        
        return $query->exists();
    }

    /**
     * Get Supplier statistics.
     * 
     * @return array Array containing various statistics
     */
    public function getStatistics(): array
    {
        return [
            'total' => $this->model->count(),
            'active' => $this->model->where('status', 'active')->count(),
            'inactive' => $this->model->where('status', 'inactive')->count(),
        ];
    }

    /**
     * Check if Supplier has related records.
     * 
     * @param int $supplierId The Supplier ID to check
     * @return bool True if has related records, false otherwise
     */
    public function hasRelatedRecords(int $supplierId): bool
    {
        $supplier = $this->findById($supplierId);
        
        if (!$supplier) {
            return false;
        }
        
        return $supplier->purchaseOrders()->exists();
    }

    /**
     * Apply filters to the query.
     * 
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param array $filters
     * @return void
     */
    protected function applyFilters($query, array $filters): void
    {
        if (isset($filters['status'])) {
            $query->where('status', $filters['status']);
        }
        
        if (isset($filters['search']) && !empty($filters['search'])) {
            $search = $filters['search'];
            $query->where(function ($q) use ($search) {
                $q->where('name', 'LIKE', "%{$search}%")
                  ->orWhere('contact_person', 'LIKE', "%{$search}%")
                  ->orWhere('phone', 'LIKE', "%{$search}%")
                  ->orWhere('email', 'LIKE', "%{$search}%");
            });
        }
    }
}