<?php

namespace App\Repositories;

use App\Models\Warehouse;
use App\Repositories\Contracts\WarehouseRepositoryInterface;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Pagination\LengthAwarePaginator;

/**
 * WarehouseRepository
 * 
 * Repository class for Warehouse model that implements WarehouseRepositoryInterface.
 * This class provides data access layer methods for Warehouse operations
 * including CRUD operations, filtering, searching, and pagination.
 * 
 * @package App\Repositories
 * @author Generated by Laravel Custom Command
 */
class WarehouseRepository implements WarehouseRepositoryInterface
{
    /**
     * The Warehouse model instance.
     * 
     * @var Warehouse
     */
    protected Warehouse $model;

    /**
     * WarehouseRepository constructor.
     * 
     * @param Warehouse $model The Warehouse model instance
     */
    public function __construct(Warehouse $model)
    {
        $this->model = $model;
    }

    /**
     * Get all Warehouses from the database.
     * 
     * This method retrieves all Warehouses records with optional eager loading
     * of related models to optimize database queries and prevent N+1 problems.
     * 
     * @param array $with Array of relationships to eager load (e.g., ['inventoryStocks', 'stockBatches'])
     * @return Collection Collection of Warehouse instances
     * 
     * @example
     * // Get all Warehouses without relationships
     * $warehouseRepository->getAll();
     * 
     * // Get all Warehouses with inventory stocks
     * $warehouseRepository->getAll(['inventoryStocks']);
     */
    public function getAll(array $with = []): Collection
    {
        $query = $this->model->newQuery();
        
        if (!empty($with)) {
            $query->with($with);
        }
        
        return $query->get();
    }

    /**
     * Get paginated Warehouses with optional filters and relationships.
     * 
     * This method provides paginated results with filtering capabilities
     * for efficient data retrieval and display in user interfaces.
     * 
     * @param array $filters Associative array of filters to apply
     * @param array $with Array of relationships to eager load
     * @param int $perPage Number of items per page (default: 15)
     * @return LengthAwarePaginator Paginated collection of Warehouse instances
     * 
     * @example
     * // Get paginated warehouses with filters
     * $filters = ['status' => 'active', 'search' => 'warehouse name'];
     * $warehouseRepository->getPaginated($filters, ['inventoryStocks'], 10);
     */
    public function getPaginated(array $filters = [], array $with = [], array $withCount = [], int $perPage = 15, string $sortBy = 'name', string $sortOrder = 'asc'): LengthAwarePaginator
    {
        $query = $this->model->newQuery();
        
        // Apply eager loading if relationships are specified
        if (!empty($with)) {
            $query->with($with);
        }
        
        // Apply relationship counting for performance optimization
        if (!empty($withCount)) {
            $query->withCount($withCount);
        }
        
        // Apply dynamic filters
        $this->applyFilters($query, $filters);
        
        // Apply secure sorting with validation
        $allowedSortFields = ['id', 'name', 'address', 'status', 'created_at', 'updated_at'];
        
        // Validate sort order
        $sortOrder = in_array(strtolower($sortOrder), ['asc', 'desc']) ? strtolower($sortOrder) : 'asc';

        // Apply sorting with field validation
        if (in_array($sortBy, $allowedSortFields)) {
            $query->orderBy($sortBy, $sortOrder);
        } else {
            // Default sorting if invalid field provided
            $query->orderBy('name', 'asc');
        }
        
        return $query->paginate($perPage);
    }

    /**
     * Find a Warehouse by its ID.
     * 
     * @param int $id The Warehouse ID to search for
     * @param array $with Array of relationships to eager load
     * @return Warehouse|null The found Warehouse instance or null if not found
     * 
     * @example
     * // Find warehouse by ID with inventory stocks
     * $warehouse = $warehouseRepository->findById(1, ['inventoryStocks']);
     */
    public function findById(int $id, array $with = []): ?Warehouse
    {
        $query = $this->model->newQuery();
        
        if (!empty($with)) {
            $query->with($with);
        }
        
        return $query->find($id);
    }

    /**
     * Find a Warehouse by its name.
     * 
     * @param string $name The Warehouse name to search for
     * @param array $with Array of relationships to eager load
     * @return Warehouse|null The found Warehouse instance or null if not found
     */
    public function findByName(string $name, array $with = []): ?Warehouse
    {
        $query = $this->model->newQuery();
        
        if (!empty($with)) {
            $query->with($with);
        }
        
        return $query->where('name', $name)->first();
    }

    /**
     * Find a Warehouse by its code.
     * 
     * @param string $code The Warehouse code to search for
     * @param array $with Array of relationships to eager load
     * @return Warehouse|null The found Warehouse instance or null if not found
     */
    public function findByCode(string $code, array $with = []): ?Warehouse
    {
        $query = $this->model->newQuery();
        
        if (!empty($with)) {
            $query->with($with);
        }
        
        return $query->where('code', $code)->first();
    }

    /**
     * Create a new Warehouse record.
     * 
     * @param array $data The data to create the Warehouse with
     * @return Warehouse The newly created Warehouse instance
     * 
     * @example
     * $data = [
     *     'name' => 'Main Warehouse',
     *     'code' => 'WH001',
     *     'address' => '123 Storage St',
     *     'phone' => '123456789',
     *     'manager_name' => 'John Manager',
     *     'status' => 'active'
     * ];
     * $warehouse = $warehouseRepository->create($data);
     */
    public function create(array $data): Warehouse
    {
        return $this->model->create($data);
    }

    /**
     * Update an existing Warehouse record.
     * 
     * @param Warehouse $warehouse The Warehouse instance to update
     * @param array $data The data to update the Warehouse with
     * @return Warehouse The updated Warehouse instance
     */
    public function update(Warehouse $warehouse, array $data): Warehouse
    {
        $warehouse->update($data);
        return $warehouse->fresh();
    }

    /**
     * Delete a Warehouse record.
     * 
     * @param Warehouse $warehouse The Warehouse instance to delete
     * @return bool True if deletion was successful, false otherwise
     */
    public function delete(Warehouse $warehouse): bool
    {
        return $warehouse->delete();
    }

    /**
     * Get Warehouses by status.
     * 
     * @param string $status The status to filter by ('active' or 'inactive')
     * @param array $with Array of relationships to eager load
     * @return Collection Collection of Warehouse instances
     */
    public function getByStatus(string $status, array $with = []): Collection
    {
        $query = $this->model->newQuery();
        
        if (!empty($with)) {
            $query->with($with);
        }
        
        return $query->where('status', $status)->get();
    }

    /**
     * Get active Warehouses.
     * 
     * @param array $with Array of relationships to eager load
     * @return Collection Collection of active Warehouse instances
     */
    public function getActiveWarehouses(array $with = []): Collection
    {
        return $this->getByStatus('active', $with);
    }

    /**
     * Search Warehouses by name, code, address, or manager name.
     * 
     * @param string $query The search query
     * @param array $with Array of relationships to eager load
     * @param int $perPage Number of items per page
     * @return LengthAwarePaginator Paginated search results
     */
    public function search(string $query, array $with = [], int $perPage = 15): LengthAwarePaginator
    {
        $queryBuilder = $this->model->newQuery();
        
        if (!empty($with)) {
            $queryBuilder->with($with);
        }
        
        $queryBuilder->where(function ($q) use ($query) {
            $q->where('name', 'LIKE', "%{$query}%")
              ->orWhere('code', 'LIKE', "%{$query}%")
              ->orWhere('address', 'LIKE', "%{$query}%")
              ->orWhere('manager_name', 'LIKE', "%{$query}%");
        });
        
        return $queryBuilder->paginate($perPage);
    }

    /**
     * Check if a Warehouse name already exists.
     * 
     * @param string $name The name to check
     * @param int|null $excludeId ID to exclude from the check (for updates)
     * @return bool True if name exists, false otherwise
     */
    public function nameExists(string $name, ?int $excludeId = null): bool
    {
        $query = $this->model->where('name', $name);
        
        if ($excludeId) {
            $query->where('id', '!=', $excludeId);
        }
        
        return $query->exists();
    }

    /**
     * Check if a Warehouse code already exists.
     * 
     * @param string $code The code to check
     * @param int|null $excludeId ID to exclude from the check (for updates)
     * @return bool True if code exists, false otherwise
     */
    public function codeExists(string $code, ?int $excludeId = null): bool
    {
        $query = $this->model->where('code', $code);
        
        if ($excludeId) {
            $query->where('id', '!=', $excludeId);
        }
        
        return $query->exists();
    }

    /**
     * Get Warehouse statistics.
     * 
     * @return array Array containing various statistics
     */
    public function getStatistics(): array
    {
        return [
            'total' => $this->model->count(),
            'active' => $this->model->where('status', 'active')->count(),
            'inactive' => $this->model->where('status', 'inactive')->count(),
        ];
    }

    /**
     * Check if Warehouse has related records.
     * 
     * @param int $warehouseId The Warehouse ID to check
     * @return bool True if has related records, false otherwise
     */
    public function hasRelatedRecords(int $warehouseId): bool
    {
        $warehouse = $this->findById($warehouseId);
        
        if (!$warehouse) {
            return false;
        }
        
        return $warehouse->inventoryStocks()->exists() || $warehouse->stockBatches()->exists();
    }

    /**
     * Apply filters to the query.
     * 
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param array $filters
     * @return void
     */
    protected function applyFilters($query, array $filters): void
    {
        if (isset($filters['status'])) {
            $query->where('status', $filters['status']);
        }
        
        if (isset($filters['search']) && !empty($filters['search'])) {
            $search = $filters['search'];
            $query->where(function ($q) use ($search) {
                $q->where('name', 'LIKE', "%{$search}%")
                  ->orWhere('code', 'LIKE', "%{$search}%")
                  ->orWhere('address', 'LIKE', "%{$search}%")
                  ->orWhere('manager_name', 'LIKE', "%{$search}%");
            });
        }
    }
}